### ISSUE TITLE
Resnet-v2 的实现

### ISSUE THREAD

**Issue by daili0015** [JJBOY/CNN-repository#1]
你好，我在网上找Resnet-v2 的实现，阅读了你的实现；其中BasicBlock和Bottleneck的搭建没啥毛病，做到了论文说的bn-relu-conv结构，以及把relu提前。
不过其中在导入预训练模型时，用的url是model_urls['resnet20']，但是代码里并没有model_urls['resnet20'])这个项目，而是pytorch官方的Resnet-v1系列模型的下载地址。
请问Resnet-v2的预训练模型的url在哪里可以找到呢？

**Comment by daili0015** [comment]
另外，在哪里可以找到Resnet-v2 的pytorch实现呢？我实在是搜索不到

**Comment by JJBOY** [comment]
> 你好，我在网上找Resnet-v2 的实现，阅读了你的实现；其中BasicBlock和Bottleneck的搭建没啥毛病，做到了论文说的bn-relu-conv结构，以及把relu提前。
> 不过其中在导入预训练模型时，用的url是model_urls['resnet20']，但是代码里并没有model_urls['resnet20'])这个项目，而是pytorch官方的Resnet-v1系列模型的下载地址。
> 请问Resnet-v2的预训练模型的url在哪里可以找到呢？
你好，resnet v2 官方是没有预训练模型的，我也没有。我只有在CIFAR10上的模型。
为了保持同一的API所以我把代码写成了这个样子，但是如果设置pretrained=True是会报错的
